spring:
  application:
    name: practice
  datasource:
    url: jdbc:postgresql://localhost:5432/practicedb
    username: postgres
    password: ratata
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect